<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqmnvzl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqmnvzl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAqmnvzl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAqmnvzl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAqmnvzl\appProdProjectContainer([
    'container.build_hash' => 'Aqmnvzl',
    'container.build_id' => '7f590e14',
    'container.build_time' => 1597917765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqmnvzl');
